"""Command-line interface for Carbon Transition DuckDB Lab."""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import typer
from rich.console import Console
from rich.table import Table

from carbon_transition_duckdb.config import ProjectPaths
from carbon_transition_duckdb.ingestion.download import download_owid_datasets
from carbon_transition_duckdb.pipeline import build_duckdb_lakehouse, compute_transition_scores
from carbon_transition_duckdb.reporting.markdown import write_report
from carbon_transition_duckdb.sample_data import generate_synthetic_owid_data
from carbon_transition_duckdb.visualization.plots import plot_top_scores

app = typer.Typer(help="Local DuckDB lakehouse for carbon-transition analytics.")
console = Console()


@app.command("sample-data")
def sample_data(
    output_dir: Path = typer.Option(Path("data/raw"), help="Directory for synthetic raw CSV files."),
    start_year: int = typer.Option(2010, help="First generated year."),
    end_year: int = typer.Option(2024, help="Last generated year."),
    seed: int = typer.Option(42, help="Random seed."),
) -> None:
    """Generate synthetic OWID-like data."""
    co2_path, energy_path = generate_synthetic_owid_data(
        output_dir=output_dir,
        start_year=start_year,
        end_year=end_year,
        seed=seed,
    )
    console.print(f"[green]Generated:[/] {co2_path}")
    console.print(f"[green]Generated:[/] {energy_path}")


@app.command("download-owid")
def download_owid(
    output_dir: Path = typer.Option(Path("data/raw"), help="Directory for downloaded CSV files."),
    overwrite: bool = typer.Option(False, help="Overwrite existing files."),
) -> None:
    """Download OWID CO2 and energy datasets."""
    files = download_owid_datasets(output_dir=output_dir, overwrite=overwrite)
    table = Table(title="Downloaded files")
    table.add_column("Name")
    table.add_column("Size bytes", justify="right")
    table.add_column("Path")
    for item in files:
        table.add_row(item.name, str(item.size_bytes), str(item.path))
    console.print(table)


@app.command("build")
def build(
    raw_dir: Path = typer.Option(Path("data/raw"), help="Directory containing raw OWID CSV files."),
    database: Path = typer.Option(
        Path("data/processed/carbon_transition.duckdb"),
        help="Path to DuckDB database.",
    ),
    export_dir: Path = typer.Option(
        Path("data/processed/marts"),
        help="Directory for exported Parquet marts.",
    ),
) -> None:
    """Build the DuckDB database and export analytical marts."""
    result = build_duckdb_lakehouse(
        ProjectPaths(raw_dir=raw_dir, database=database, export_dir=export_dir)
    )
    console.print(f"[green]Database:[/] {result.database}")
    console.print(f"[green]Export dir:[/] {result.export_dir}")
    console.print(f"[green]Mart table:[/] {result.mart_table}")
    console.print(f"[green]Rows:[/] {result.row_count}")


@app.command("score")
def score(
    database: Path = typer.Option(
        Path("data/processed/carbon_transition.duckdb"),
        help="Path to DuckDB database.",
    ),
    output: Path = typer.Option(
        Path("reports/sample_run/transition_scores.csv"),
        help="Output CSV with scores.",
    ),
    include_aggregates: bool = typer.Option(
        False,
        help="Include aggregate entities such as World or Europe.",
    ),
) -> None:
    """Compute transition-risk scores from the DuckDB mart."""
    scores = compute_transition_scores(database=database, exclude_aggregates=not include_aggregates)
    output.parent.mkdir(parents=True, exist_ok=True)
    scores.to_csv(output, index=False)
    console.print(f"[green]Wrote scores:[/] {output}")


@app.command("report")
def report(
    scores: Path = typer.Option(
        Path("reports/sample_run/transition_scores.csv"),
        help="Scores CSV generated by the score command.",
    ),
    output: Path = typer.Option(
        Path("reports/sample_run/transition_report.md"),
        help="Markdown report output path.",
    ),
    title: str = typer.Option("Carbon Transition Risk Report", help="Report title."),
    top_n: int = typer.Option(15, help="Number of highest-risk rows to show."),
    chart: Path | None = typer.Option(None, help="Optional path for a top-score chart."),
) -> None:
    """Generate a Markdown report from transition scores."""
    frame = pd.read_csv(scores)
    write_report(frame, output_path=output, title=title, top_n=top_n)
    console.print(f"[green]Wrote report:[/] {output}")

    if chart is not None:
        plot_top_scores(frame, output_path=chart, top_n=top_n)
        console.print(f"[green]Wrote chart:[/] {chart}")
